import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Shield } from "lucide-react";
import { Link } from "wouter";

export default function PrivacyPolicy() {
  return (
    <div className="flex-1 bg-gradient-to-br from-background via-background to-muted/30">
      <div className="container max-w-4xl mx-auto px-4 py-8">
        <div className="mb-6">
          <Link href="/">
            <Button variant="ghost" size="sm">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Home
            </Button>
          </Link>
        </div>

        <Card>
          <CardHeader className="border-b">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-primary/10">
                <Shield className="h-6 w-6 text-primary" />
              </div>
              <div>
                <CardTitle className="text-2xl">Privacy Policy</CardTitle>
                <p className="text-sm text-muted-foreground mt-1">
                  Last updated: December 24, 2025
                </p>
              </div>
            </div>
          </CardHeader>

          <CardContent className="prose prose-sm dark:prose-invert max-w-none pt-6 space-y-8">

            {/* INTRO */}
            <section>
              <h2 className="text-xl font-semibold mb-3">1. Introduction</h2>
              <p className="text-muted-foreground">
                Temp Mail Get ("we", "our", "us") provides a temporary email service
                through our website and Android application. This Privacy Policy
                explains how data is collected, used, stored, and deleted based
                strictly on how our system operates.
              </p>
            </section>

            {/* WEBSITE */}
            <section>
              <h2 className="text-xl font-semibold mb-3">
                2. Website Privacy Policy (tempmailget.com)
              </h2>

              <h3 className="font-semibold">Data Collected</h3>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Temporary email addresses generated by users</li>
                <li>Emails received at those addresses</li>
                <li>IP address and request metadata (security & rate-limiting)</li>
                <li>Basic usage logs for abuse prevention</li>
              </ul>

              <h3 className="font-semibold mt-4">Purpose</h3>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Provide temporary inbox functionality</li>
                <li>Prevent spam, abuse, and automated misuse</li>
                <li>Ensure service reliability</li>
              </ul>

              <h3 className="font-semibold mt-4">Retention</h3>
              <p className="text-muted-foreground">
                Temporary emails and inbox data are automatically deleted after a
                limited time or when no longer required for service operation.
              </p>
            </section>

            {/* ANDROID APP */}
            <section>
              <h2 className="text-xl font-semibold mb-3">
                3. TEMP MAIL (APK) Privacy Policy
              </h2>

              <h3 className="font-semibold">Account & Authentication</h3>
              <p className="text-muted-foreground">
               
              </p>

              <h3 className="font-semibold mt-4">Data Collected</h3>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li></li>
                <li>Generated email addresses and aliases</li>
                <li>Emails received in temporary inboxes</li>
                <li>Crash logs and basic app interaction data</li>
                <li>Device or session identifiers for security</li>
              </ul>

              <h3 className="font-semibold mt-4">Purpose</h3>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Provide temporary email and alias functionality</li>
                <li>Associate inboxes with user accounts</li>
                <li>Prevent abuse, spam, and excessive requests</li>
                <li>Maintain app stability and performance</li>
              </ul>

              <h3 className="font-semibold mt-4">Data Sharing</h3>
              <p className="text-muted-foreground">
                We do <strong>not</strong> sell, rent, or share user data with
                advertisers or external third parties.
              </p>

              <h3 className="font-semibold mt-4">Retention</h3>
              <p className="text-muted-foreground">
                Emails and aliases are stored only as long as required to provide
                the service and are automatically deleted or removed upon expiry
                or account deletion.
              </p>
            </section>

            {/* DELETION */}
            <section>
              <h2 className="text-xl font-semibold mb-3">4. Account & Data Deletion</h2>
              <p className="text-muted-foreground">
                Users may request deletion of their account and associated data at any time.
              </p>

              <p className="text-muted-foreground mt-3">
                You can request deletion by visiting:
              </p>

              <p>
                <a
                  href="https://tempmailget.com/delete-account"
                  className="text-primary hover:underline"
                >
                  https://tempmailget.com/delete-account
                </a>
              </p>

              <p className="text-muted-foreground mt-3">
                If you are unable to access the deletion page, you may also contact us directly:
              </p>

              <p>
                <a
                  href="https://tempmailget.com/contact"
                  className="text-primary hover:underline"
                >
                  https://tempmailget.com/contact
                </a>
              </p>

              <p className="text-muted-foreground mt-3">
                All valid deletion requests are processed within 24–72 hours,
                except where legal retention is required.
              </p>
            </section>

            {/* SECURITY */}
            <section>
              <h2 className="text-xl font-semibold mb-3">5. Security</h2>
              <p className="text-muted-foreground">
                All data is transmitted using encrypted HTTPS connections.
                Access controls, rate limiting, and monitoring are used
                to protect against unauthorized access and abuse.
              </p>
            </section>

            {/* CHILDREN */}
            <section>
              <h2 className="text-xl font-semibold mb-3">6. Children’s Privacy</h2>
              <p className="text-muted-foreground">
                Our services are intended for users aged 18 and above.
                We do not knowingly collect data from children.
              </p>
            </section>

            {/* CONTACT */}
            <section>
              <h2 className="text-xl font-semibold mb-3">7. Contact</h2>
              <p className="text-muted-foreground">
                For privacy-related questions or requests:
              </p>
              <p>
                <Link href="/contact" className="text-primary hover:underline">
                  https://tempmailget.com/contact
                </Link>
              </p>
            </section>

          </CardContent>
        </Card>
      </div>
    </div>
  );
}
